#!/stage1/busybox sh
echo "OHAI, stage1 init starting" > /dev/kmsg
export _PATH="$PATH"
export PATH=/stage1

force_recovery="0"

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mkdir /proc
busybox mkdir /sys
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys


busybox sleep 5



busybox echo "force_recovery: $force_recovery"
busybox mkdir bada_user
busybox chmod 0777 /bada_user
busybox mkdir /system
busybox mkdir /cache
busybox mkdir /data
busybox mount -t ext4 /dev/block/mmcblk1p3 /system
busybox mount -t ext4 /dev/block/mmcblk1p2 /cache
busybox mount -t vfat /dev/block/mmcblk0p2 /bada_user
image=/stage1/ramdisk.cpio

if  busybox grep -q "recovery" /proc/cmdline || busybox grep -q "init=/init bootmode=0 loglevel=0 androidboot.serialno=0000045600000123 bootmode=2" /proc/cmdline || busybox grep -q "init=/init bootmode=0 loglevel=4 androidboot.serialno=0000045600000123 bootmode=2" /proc/cmdline || busybox grep -q "bootmode=2" /proc/cmdline || busybox test -e /cache/.startrecovery || busybox grep -q bootmode=2 /proc/cmdline  ; then
	# recovery boot
	busybox rm -fr /cache/.startrecovery
	image=/stage1/ramdisk-recovery.cpio

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

busybox umount /cache
busybox umount /system
busybox umount /bada_user



busybox cpio -i < $image

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
echo "stage1 log:" > /dev/kmsg
busybox cat boot.txt > /dev/kmsg
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
